### ISSUE TITLE
Cleanup Config

### ISSUE THREAD

**Issue by mkendler** [redmod-team/profit#55]
Bring Config class and user interface in a clear form.

- [x] enhance Config options (also solves #29)
- [x] resolve path problems (also solves #19, #41)
- [x] standardize code formatting
- [x] update doc with Config options
- [x] make variable functions easily customizable (also solves #21)
- [x] optionally include Independent variable in inputs and treat as another parameter
- [x] save output as .txt or .hdf5
- [x] .py file with dict should also be a valid config file besides .yaml
